name: 🚀  Release

on:
  push:
    branches: [master]

jobs:
  release:
    name: 🚀  Publish GitHub Release
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.release.outputs.release-version }}
      released: ${{ steps.release.outputs.new-release-published }}
    steps:
      - name: 🚚  Checkout project
        uses: actions/checkout@v4

      - id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PEM }}
          permission-contents: write
          permission-issues: write
          permission-pull-requests: write

      - name: 🚀  Publish Release
        id: release
        uses: cycjimmy/semantic-release-action@v6
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

  update-readme:
    name: 📖  Update version in README
    needs: [release]
    if: needs.release.outputs.released == 'true'
    uses: ./.github/workflows/update-readme.yml
    with:
      release-version: ${{ needs.release.outputs.release-version }}
